#!/bin/bash
#
#Algus
#

echo -n "Mis on sinu vanus? "
read vanus

###IF osa

if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "oled laps"
elif test $vanus -gt 11 -a $vanus -lt 18
then
	echo "Oled nooruk"
elif [ $vanus -gt 18 -a $vanus -lt 63 ]
then
	echo "oled täiskasvanu"
elif [ $vanus -ge 63 ]
then
	echo "oled senioor"
else
	echo "Viga!"
fi

#
#Lõpp
#
