#!/bin/bash
#
#Arvu sisestus
#

##Küsib arvu
echo -n "Sisesta suvaline täisarv: "
read arv

##Arvutamine

while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done

##Tulemus

echo "sende arvude summa on $summa"

#
#Lõpp
#
