#!/bin/bash
#
#Kasutaja tervitus
#
#Algus

who | cut -f1 -d" " | cut -f2 -d"." > perenimi #Lõikab perenime (2. element)
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi #Lõikab eesnime (1. element)
paste -d"." perenimi eesnimi > nimed #kleebib failid järjekorras kokku
cat nimed | sort | uniq #sordib ja võtab korduvad välja

#Kõik \_(:D)_/
#
