#!/bin/bash

#Kasutaja tervitus

echo -n "Tere "
echo -n `who am i | cut -c1 | tr [:lower:] [:upper:]` #Esimene täht suureks
echo -n `who am i | cut -c2- | cut -f1 -d" "` #Lõikab kõik tähed alates teisest
echo "!"

#Kõik \_(:D)_/

