#!/bin/bash
#
#

echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv: "
read mitu

###

for (( i = 1; i <= $rida; i++ ))
do
	for (( j = 1; j <= 1; j++ ))
	do
		echo -n "$i. "
	done
	for (( z = 1; z <= $mitu; z++ ))
	do
		echo -n "*"
	done
	echo ""
done
